app:
    resource: "@AppBundle/Controller/"
    type:     annotation

backend:
    resource: "@AppBundle/Controller/Backend"
    type:     annotation
    prefix: "/{_locale}/admin"
    requirements:
      _locale: en|ru

frontend:
    resource: "@AppBundle/Controller/Frontend"
    type:     annotation
    prefix: "/"

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout