app:
    resource: "@AppBundle/Controller/"
    type:     annotation

backend:
    resource: "@AppBundle/Controller/Backend"
    type:     annotation
    prefix: "/admin"

frontend:
    resource: "@AppBundle/Controller/Frontend"
    type:     annotation
    prefix: "/"

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout