security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        main:
            entity: { class: AppBundle:User, property: email }

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
                username_parameter: appbundle_authorization[email]
                password_parameter: appbundle_authorization[password]
                default_target_path: /
                always_use_default_target_path: true
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                remember_me_parameter: appbundle_authorization[remember_me]
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: /admin/.*, roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }